production:
  adapter: postgresql
  encoding: unicode
  database: smark-kiosk-production
  username: smart-kiosk-admin
  password: SmartKiosk
  host: localhost
  pool: 50
  timeout: 100000

staging:
  adapter: postgresql
  encoding: unicode
  database: smark-kiosk-staging
  username: smart-kiosk-admin
  password: SmartKiosk
  host: localhost
  pool: 50
  timeout: 100000