production:
  adapter: postgresql
  encoding: unicode
  database: sm_prod
  username: smadmin
  password: $martKiosk15
  host: localhost
  pool: 50
  timeout: 100000

staging:
  adapter: postgresql
  encoding: unicode
  database: sm_prod
  username: smadmin
  password: $martKiosk15
  host: localhost
  pool: 50
  timeout: 100000